### ISSUE TITLE
Add documentation to LED.msg

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/somanet_msgs#2]
Marco, please add documentation about the available LED patterns based on our serial protocol specification to the `somanet_msgs/LED` message: https://github.com/yujinrobot/somanet_msgs/blob/indigo/msg/LED.msg

Thanks.

**Comment by Marco-Andarcia** [comment]
updated in commit d84c2f8438cca43b9b9c280fa9b9a536c187f973

**Comment by bit-pirate** [comment]
Marco, in case you are not aware of it already, you can close issues directly from the commit message. For example: `Updated description of led message. (fixes #2)`.

This works on both Github (https://help.github.com/articles/closing-issues-via-commit-messages/) and Bitbucket (https://confluence.atlassian.com/display/BITBUCKET/Resolve+issues+automatically+when+users+push+code).

**Comment by bit-pirate** [comment]
One more thing: Please use constants for the different LED patterns: http://wiki.ros.org/msg#Constants

See [`somanet_msgs/SmartBatteryStatus`](https://github.com/yujinrobot/somanet_msgs/blob/indigo/msg/SmartBatteryStatus.msg) as example.

**Comment by Marco-Andarcia** [comment]
added the new definitions similar to the SmartBattery example. commit 0e21d1b2e37b6d0c9a78a1d17c56b37f3d1ace85

**Comment by bit-pirate** [comment]
Nice! :neckbeard:
