### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/somanet_msgs#8]
@Marco-Andarcia is branch `messages_rename_marco` still needed? If not, please delete.

@stonier is branch `gocart_v2_testing` still needed? If not, please delete.

**Comment by Marco-Andarcia** [comment]
yeah the branch was already merged I will delete it.

On Thu, Dec 10, 2015 at 3:37 PM, Marcus Liebhardt <notifications@github.com>
wrote:

> Assigned #8 <https://github.com/yujinrobot/somanet_msgs/issues/8> to
> @Marco-Andarcia <https://github.com/Marco-Andarcia>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yujinrobot/somanet_msgs/issues/8#event-487820008>.
>



-- 

*Marco Andarcia.*
*Controls Software Engineer. *

**Comment by Marco-Andarcia** [comment]
I just deleted the stale branches.

**Comment by bit-pirate** [comment]
:+1:
